### ISSUE TITLE
libGLU  linker issue 

### ISSUE THREAD

**Issue by JohnVV** [CelestiaProject/Celestia#1606]
**Describe the bug**
 Linker error on current git clone for cmodview

/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/cmodview.dir/modelviewwidget.cpp.o: in function `ModelViewWidget::paintGL()':
modelviewwidget.cpp:(.text+0x621f): undefined reference to `gluPerspective'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: modelviewwidget.cpp:(.text+0x67f6): undefined reference to `gluErrorString'
collect2: error: ld returned 1 exit status

**To Reproduce**
build on the current updated OpenSUSE 15.4 ,with libGLU.so.1.3.1 

**Expected behavior**
build completes 

this dose look to be a error on my end with the current libGLU 
the cmodeview code looks like it needs to be updated .

**Comment by munix9** [comment]
celestia and tools are built without problems on OBS for openSUSE, Debian and Ubuntu - also cmodview.
See 
https://build.opensuse.org/package/live_build_log/home:munix9:unstable/celestia/15.4/x86_64
https://build.opensuse.org/public/build/home:munix9:unstable/15.4/x86_64/celestia/_log

**Comment by JohnVV** [comment]
cmodview is missing from "celestia-tools-1.7.0~git20230226+78d39ca-lp154.711.1.x86_64.rpm "

**Comment by munix9** [comment]
```
$ cnf cmodview
                      
Program 'cmodview' is present in package 'celestia-tools-qt', which is installed on your system.

Absolute path to 'cmodview' is '/usr/bin/cmodview'. Please check your $PATH variable to see whether it contains the mentioned path.
```

**Comment by JohnVV** [comment]
found a solution using "ccmake" 
added
CMAKE_CXX_FLAGS                   -Wl,--copy-dt-needed-entries
CMAKE_SHARED_LINKER_FLAGS         -lGL
